eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka
spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      routes[0]:
        id: discovery-server
        uri: http://localhost:8761
        predicates[0]: Path=/eureka/web
        filters[0]: SetPath=/
      routes[1]:
        id: discovery-server-static
        uri: http://localhost:8761
        predicates[0]: Path=/eureka/**
      routes[2]:
        id: storage-service
        uri: lb://storage-service
        predicates[0]: Path=/api/storage
      routes[3]:
        id: notification-service
        uri: lb://notification-service
        predicates[0]: Path=/api/notification
      routes[4]:
        id: logger-service
        uri: lb://logger-service
        predicates[0]: Path=/api/log
  zipkin:
    base-url: http://localhost:9411
  sleuth:
    sampler:
      probability: 1.0
logging:
  level:
    root: INFO
    org.springframework.cloud.gateway.route.RouteDefinitionLocator: INFO
    org.springframework.cloud.gateway: TRACE