server:
  port: 0
spring:
  application:
    name: logger-service
  datasource:
    url: jdbc:postgresql://localhost:5432/logger
    username: admin
    password: admin
  jpa:
    hibernate:
      ddl-auto: update
  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest